const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let hugs=0,candleCount=0,flowers=0;const modal=$('#modal');function openModal(html){$('#modalContent').innerHTML=html;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}$('#close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};function toast(t){$('#toast').textContent=t;$('#toast').className='toast';setTimeout(()=>$('#toast').className='',2200)}function burst(symbol='💙',n=18){for(let i=0;i<n;i++){let e=document.createElement('div');e.className='burst';e.textContent=symbol;e.style.left=Math.random()*100+'vw';e.style.top=(60+Math.random()*30)+'vh';document.body.append(e);setTimeout(()=>e.remove(),2100)}}
// 1-10: atmosphere, typing, counter, music, surprises
const text='Today, every star is celebrating you...';let k=0;setInterval(()=>{$('#typing').textContent=text.slice(0,k++% (text.length+1))},90);$('#musicBtn').onclick=()=>{let m=$('#music');if(m.paused){m.play().then(()=>toast('Music started 🎵')).catch(()=>toast('Tap again to allow music'))}else{m.pause();toast('Music paused')}};$('#surprise').onclick=()=>{const a=['You are someone’s favourite notification 💙','Your smile deserves its own sunrise 🌅','A thousand hugs are flying your way 🤗','You make ordinary days feel special ✨'];openModal('<h2>🎁 Surprise</h2><p>'+a[Math.floor(Math.random()*a.length)]+'</p>');burst()};setInterval(()=>{$('#counter').textContent=++hugs},2500);$('#days').textContent=365;
// 11-20: modal letters and wish
$('[data-open="wish"]').onclick=()=>openModal(`<h2>✨ Make a Wish</h2><p>Close your eyes, make one secret wish, and press the heart.</p><button onclick="burst('💙',35);toast('Your wish is safe with the stars ✨');closeModal()">💙 Send wish</button>`);$('[data-open="letter"]').onclick=()=>openModal('<h2>💌 For My Jaanu</h2><p>Happy birthday, meri jaan. May every worry become lighter, every dream come closer, and every day remind you how precious you are. I cannot promise a perfect world, but I can wish you courage, peace, laughter, respect and endless reasons to smile. Keep shining, birthday star. 💙🌹</p><p>Always be your beautiful self.</p>');
// 21-30: garden
function renderGarden(){const g=$('#garden');g.innerHTML='';for(let i=0;i<Math.max(6,flowers+6);i++){let d=document.createElement('div');d.className='flower pop';d.innerHTML=['🌷','🌹','🌻','🌸','💙'][i%5]+'<small>love flower '+(i+1)+'</small>';g.append(d)}}renderGarden();$('#grow').onclick=()=>{flowers++;renderGarden();burst('🌸',8)};$('#water').onclick=()=>{toast('The garden is glowing with love 💧');burst('💧',15)};
// 31-45: gallery
const gallery=$('#gallery');for(let i=1;i<=10;i++){let d=document.createElement('div');d.className='photo pop';d.innerHTML=`<img src="rm${i}.jpg" alt="Memory ${i}"><b>Memory ${i}</b>`;d.onclick=()=>openModal(`<h2>📸 Memory ${i}</h2><img src="rm${i}.jpg" style="width:100%;border-radius:18px" onerror="this.style.display='none'"><p>Every memory deserves a little sparkle. 💙</p>`);gallery.append(d)}
// 46-60: games
$('#heartGame').onclick=()=>{let score=0;const id=setInterval(()=>{score++;burst('💗',1);$('#gameOutput').textContent='Hearts caught: '+score+'/10';if(score>=10){clearInterval(id);$('#gameOutput').textContent='You caught 10 hearts! Big hug unlocked 🤗';}},350)};$('#quiz').onclick=()=>openModal(`<h2>🧠 Birthday Quiz</h2><p>What should a birthday star receive?</p><button onclick="quizAnswer('cake')">Cake 🎂</button><button onclick="quizAnswer('love')">Love 💙</button><button onclick="quizAnswer('all')">All of them ✨</button>`);window.quizAnswer=a=>{closeModal();$('#gameOutput').textContent=a==='all'?'Correct! You deserve everything beautiful 💙':'Correct answer: all the love and cake! 🎂';burst()};$('#luck').onclick=()=>$('#gameOutput').textContent=['A beautiful surprise is waiting for you ✨','Your smile will brighten someone’s day 🌷','Your dreams deserve patience and courage 🌙','You are more loved than you know 💙'][Math.floor(Math.random()*4)];$('#compliment').onclick=()=>$('#gameOutput').textContent=['Your heart is precious.','Your presence feels like home.','Your smile is a tiny sunrise.','You deserve gentle love and big dreams.'][Math.floor(Math.random()*4)];
// 61-70 notes
let notes=['You are my favourite kind of happiness. 💙','May your year be softer than clouds. ☁️','Your dreams are worth chasing. 🌙','You deserve love that feels safe. 🌷','Never forget how special you are. ✨'];function renderNotes(){$('#notes').innerHTML=notes.map((n,i)=>`<div class="note pop"><span>💌 ${i+1}</span><p>${n}</p></div>`).join('')}renderNotes();$('#newNote').onclick=()=>{notes.push(['I am cheering for you. 🌟','Your happiness matters. 💙','One more reason to smile: you exist. 🌸'][notes.length%3]);renderNotes();};
// 71-78 cake
$('#candles').onclick=()=>{candleCount++;$('#cake').textContent='🎂'+'🕯️'.repeat(candleCount);$('#cakeText').textContent=candleCount+' candle(s) glowing for you.'};$('#blow').onclick=()=>{$('#cake').textContent='🍰';$('#cakeText').textContent='Wish released into the universe ✨';burst('✨',25)};$('#slice').onclick=()=>{$('#cake').textContent='🍰🍰';$('#cakeText').textContent='A slice for you, a slice for happiness!'};
// 79-85 mood
$$('[data-mood]').forEach(b=>b.onclick=()=>{let m=b.dataset.mood;document.body.style.background={romantic:'radial-gradient(circle at top,#6c214f,#160b27)',cute:'radial-gradient(circle at top,#7a4774,#17132d)',royal:'radial-gradient(circle at top,#55421e,#100d27)',dreamy:'radial-gradient(circle at top,#203d78,#080b22)'}[m];$('#moodText').textContent='Mood selected: '+m+'. The whole sky is celebrating you.';burst(m==='cute'?'🐻':'💙',10)});
// 86-92 future edit
$('#editFuture').onclick=()=>openModal('<h2>✍️ Your future note</h2><textarea id="futureEdit" style="width:100%;min-height:140px;border-radius:15px;padding:12px">'+$('#future').textContent+'</textarea><button onclick="saveFuture()">Save note</button>');window.saveFuture=()=>{$('#future').textContent=$('#futureEdit').value;closeModal();toast('Your note was updated 💙')};
// 93-97 wish wall
$('#postWish').onclick=()=>{let v=$('#wishInput').value.trim();if(!v)return toast('Write a wish first ✨');let d=document.createElement('span');d.className='wish';d.textContent='💙 '+v;$('#wishWall').append(d);$('#wishInput').value='';burst('🌟',8)};
// 98-100 finale and keyboard accessibility
$('#finale').onclick=()=>{const box=$('#finaleBox');box.classList.remove('hidden');box.innerHTML='<h3>🌌 The sky is yours</h3><p>May your next chapter be full of health, peace, laughter, loyal people, exciting opportunities and beautiful memories. Happy Birthday, Jaanu. 💙🎂💋</p>';burst('💙',45)};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
